# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.cache/wt [current_project]
set_property parent.project_path D:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:genesys2:part0:1.1 [current_project]
set_property ip_repo_paths d:/vivado/project/create_core_i2c [current_project]
set_property ip_output_repo d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/new/top_cpu.v
add_files D:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_axi_apb_bridge_0_0/design_1_axi_apb_bridge_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files D:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/bd/design_1/design_1.bd]

read_ip -quiet D:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]
set_property is_locked true [get_files D:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/sources_1/ip/ila_0/ila_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/constrs_1/new/constr_1.xdc
set_property used_in_implementation false [get_files D:/vivado/project/test_core_apb_i2c/test_core_apb_i2c.srcs/constrs_1/new/constr_1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top_cpu -part xc7k325tffg900-2


write_checkpoint -force -noxdef top_cpu.dcp

catch { report_utilization -file top_cpu_utilization_synth.rpt -pb top_cpu_utilization_synth.pb }
